### ISSUE TITLE
Offline map and offline navigation dynamic

### ISSUE THREAD

**Issue by TikTak123** [parthdave93/OfflineMapAndroidDemo#1]
Is it possible to load a map and route it dynamic for offline navigation?

**Comment by parthdave93** [comment]
to load the map you need to download map file configure or upload it to your server would be better or find mapbox I guess it provides offline maps, as open street maps provide city and country, not specific region and file size is very big so parse out using omosis library.
also for offline navigation you need to look for graphhopper, it is best open source library for finding routes offline.

**Comment by TikTak123** [comment]
On the graphhopper account, I have seen many examples and in all the sample maps and offline navigation of the cook in advance. But I need it to be dynamic. For example, the user enters the application, the application determines the location of the user and in a certain radius orders the map and data for offline navigation and so there is a preparation for offline application.

**Comment by TikTak123** [comment]
In all examples, navigation is prepared in advance for a specific location.

**Comment by parthdave93** [comment]
Check MainActivity where there's getDirections method, I don't know if it's working or not as repository uploaded long time ago for others.
But if it's not working let me know.
Other than that that method contains firstPoint and lastPoint which is defined in variable declaration but yah you can change it and call it for different values.
