### ISSUE TITLE
app crashing

### ISSUE THREAD

**Issue by shivamc98** [parthdave93/OfflineMapAndroidDemo#2]
i tried to run this module . but  its crashing. 
Where is the tenerife.osm file

**Comment by parthdave93** [comment]
Actually you don't need tenerife.osm file as per current code. that osm file was huge like 800-900mb so i skipped it and cut it for map file which you can see in source code. but still you want it then search for http://download.geofabrik.de/africa/canary-islands.html this link or in google if you will still not getting that file i will search for the backup of that thing or on internet.
